version: '2'

services: 
  webapp:
    image: wojewodkainteca/family:webapp
    ports:
      - "127.0.0.1:4200:4200"
    networks:
      - pgsql_net
    links:
      - api

  database:
    image: wojewodkainteca/family:database
    ports: 
      - 5433:5432
    networks:
      - pgsql_net
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: wojewodkainteca/family:api
    build:
      context: .
    depends_on:
      - database
    links:
      - database
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - pgsql_net
      

networks:
  pgsql_net:
    driver: bridge

volumes: 
  pgdata: